executor:
  name: sb_playwright
  class: medium

steps:
  - git-shallow-clone/checkout_advanced:
      clone_options: '--depth 1 --verbose'
  - attach_workspace:
      at: /tmp
  - run:
      name: Install dependencies
      command: yarn install --no-immutable
      working_directory: test-storybooks/portable-stories-kitchen-sink/react-vitest-3
      environment:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
  - run:
      name: Run E2E tests
      command: yarn playwright-e2e
      working_directory: test-storybooks/portable-stories-kitchen-sink/react-vitest-3
  - store_test_results:
      path: storybook/test-results
  - store_artifacts:
      path: storybook/test-storybooks/portable-stories-kitchen-sink/react-vitest-3/test-results/
      destination: playwright
  - report-workflow-on-failure
