executor:
  name: sb_playwright
  class: medium

steps:
  - git-shallow-clone/checkout_advanced:
      clone_options: '--depth 1 --verbose'
  - attach_workspace:
      at: /tmp
  - run:
      name: Install dependencies
      command: yarn install --no-immutable
      working_directory: test-storybooks/yarn-pnp
      environment:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
  - run:
      name: Run Storybook smoke test
      command: yarn storybook --smoke-test
      working_directory: test-storybooks/yarn-pnp

  - report-workflow-on-failure
