executor:
  name: sb_playwright
  class: medium

steps:
  - git-shallow-clone/checkout_advanced:
      clone_options: '--depth 1 --verbose'
  - attach_workspace:
      at: .
  - run:
      name: Install dependencies
      command: yarn install
      working_directory: test-storybooks/yarn-pnp
  - run:
      name: Run Storybook smoke test
      command: yarn storybook --smoke-test
      working_directory: test-storybooks/yarn-pnp

  - report-workflow-on-failure
